[package]
name = "observer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
clearscreen = "2.0.1"
device_query = "1.1.3"
futures = "0.3.28"
tokio-util = { version = "0.7.10", features = ["full"] }
uuid = { version = "1.5.0", features = ["v4"] }